### ISSUE TITLE
Ønsker å kunne kopiere fra søkeresultat

### ISSUE THREAD

**Issue by DigdirAme** [Altinn/altinn-desktop-tool#11]
Ønsker mulighet for å kopiere (f.eks fødselsnummer, e-post, mobilnummer) fra søkeresultat. Se eksempler markert med gult her: 
![image](https://user-images.githubusercontent.com/94672791/153598756-e74f60d4-4330-42b4-9f96-7a0015705931.png)

**Comment by espenhalsen** [comment]
God Morgen! Noe slikt som tenkes her? @DigdirAme 
[Kopifunksjon Video](https://github.com/Altinn/altinn-desktop-tool/assets/89974012/754948be-4252-4d5d-a488-0355da818bf8)

**Comment by DigdirAme** [comment]
@espenhalsen Midt i blinken, ser veldig bra ut :)
